"""MUHIDE v2 Ingestion Adapter — Bulk Import to Master Data.

Handles the MUHIDE v2 dataset import into the SalesOS Master Data platform.
Designed for bulk operations with batch inserts, chunked processing, and
idempotent re-import support.

Key design decisions:
- MA-####### IDs are preserved as legacy aliases, never as Global IDs
- Global IDs are generated by ID Registry (G-C-XXXXXXXX)
- Source rows are immutable after insert
- Duplicate source keys are handled with ON CONFLICT DO NOTHING
- Batch inserts use executemany for performance
- Progress tracking enables resumable execution
"""

from __future__ import annotations

import csv
import io
import json
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.entity_resolution.id_registry import generate_global_id
from app.modules.entity_resolution.resolution_policy import normalize_cr


# ── Constants ────────────────────────────────────────────────────────────────

LEGACY_MUHIDE_MA_ID = "LEGACY_MUHIDE_MA_ID"
LEGACY_MUHIDE_ROW_ID = "LEGACY_MUHIDE_ROW_ID"
LEGACY_MUHIDE_CR = "LEGACY_MUHIDE_CR"
LEGACY_MUHIDE_APOLLO_ACCOUNT = "LEGACY_MUHIDE_APOLLO_ACCOUNT"
LEGACY_MUHIDE_APOLLO_CONTACT = "LEGACY_MUHIDE_APOLLO_CONTACT"
LEGACY_MUHIDE_REVIEW_CLUSTER = "LEGACY_MUHIDE_REVIEW_CLUSTER"

BATCH_SIZE = 5000


# ── Helpers ──────────────────────────────────────────────────────────────────

def _now() -> datetime:
    return datetime.now(UTC)


def _parse_ma_id(ma_id: str) -> str | None:
    """Extract MA-####### from a string, return None if invalid."""
    if not ma_id:
        return None
    s = str(ma_id).strip()
    if s.startswith("MA-") and s[3:].isdigit():
        return s
    return None


def _safe_str(val: Any) -> str | None:
    """Convert value to string, return None for empty/NaN."""
    if val is None:
        return None
    s = str(val).strip()
    if not s or s.lower() in ("none", "nan", "null", "n/a", ""):
        return None
    return s


# ── Source File Registration ─────────────────────────────────────────────────


async def register_muhide_source_file(
    session: AsyncSession,
    tenant_id: str,
    filename: str,
    file_path: str,
    row_count: int,
    source_system: str = "muhide_v2",
    uploaded_by: str = "system",
) -> str:
    """Register a MUHIDE source file in md_source_files.

    Returns the file ID.
    """
    import hashlib

    # Compute hash if file exists
    file_hash = "unknown"
    file_size = 0
    mime_type = "text/csv"
    try:
        p = Path(file_path)
        if p.exists():
            content = p.read_bytes()
            file_hash = hashlib.sha256(content).hexdigest()
            file_size = len(content)
            if file_path.endswith(".parquet"):
                mime_type = "application/octet-stream"
            elif file_path.endswith(".xlsx"):
                mime_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    except Exception:
        pass

    file_id = str(uuid.uuid4())
    now = _now()

    await session.execute(
        text(
            "INSERT INTO md_source_files "
            "(id, tenant_id, filename, storage_path, file_hash_sha256, file_size_bytes, "
            "mime_type, sheet_count, total_rows, source_system, uploaded_by, uploaded_at, status) "
            "VALUES (:id, :tenant_id, :filename, :path, :hash, :size, "
            ":mime, 1, :rows, :source, :by, :now, 'completed') "
            "ON CONFLICT DO NOTHING"
        ),
        {
            "id": file_id,
            "tenant_id": tenant_id,
            "filename": filename,
            "path": file_path,
            "hash": file_hash,
            "size": file_size,
            "mime": mime_type,
            "rows": row_count,
            "source": source_system,
            "by": uploaded_by,
            "now": now,
        },
    )

    return file_id


# ── Bulk Source Row Ingestion ────────────────────────────────────────────────


async def bulk_insert_source_rows(
    session: AsyncSession,
    tenant_id: str,
    source_file_id: str,
    source_id: str,
    rows: list[dict[str, Any]],
    entity_type: str = "company",
) -> int:
    """Bulk insert source rows with batch processing.

    Each row dict must have at minimum:
    - source_record_id: str
    - raw_payload: dict

    Returns count of rows inserted.
    """
    now = _now()
    inserted = 0

    # Process in batches
    for i in range(0, len(rows), BATCH_SIZE):
        batch = rows[i:i + BATCH_SIZE]
        batch_params = []

        for idx, row in enumerate(batch):
            row_id = str(uuid.uuid4())
            source_record_id = str(row.get("source_record_id", f"ROW-{i + idx}"))
            raw_payload = row.get("raw_payload", row)

            batch_params.append({
                "id": row_id,
                "tenant_id": tenant_id,
                "file_id": source_file_id,
                "source_id": source_id,
                "source_record_id": source_record_id,
                "row_number": i + idx,
                "payload": json.dumps(raw_payload, ensure_ascii=False, default=str),
                "entity_type": entity_type,
                "now": now,
            })

        if batch_params:
            result = await session.execute(
                text(
                    "INSERT INTO md_source_rows "
                    "(id, tenant_id, source_file_id, source_id, source_record_id, row_number, "
                    "raw_payload, entity_type, resolution_status, created_at) "
                    "VALUES (:id, :tenant_id, :file_id, :source_id, "
                    ":source_record_id, :row_number, "
                    "CAST(:payload AS JSONB), :entity_type, 'pending', :now) "
                    "ON CONFLICT (source_id, source_record_id) DO NOTHING"
                ),
                batch_params,
            )
            batch_inserted = getattr(result, "rowcount", None)
            if not isinstance(batch_inserted, int) or batch_inserted < 0:
                raise RuntimeError(
                    "Database driver did not report the number of inserted source rows"
                )
            inserted += batch_inserted

    return inserted


# ── Global Entity Creation ──────────────────────────────────────────────────


async def create_global_company_from_muhide(
    session: AsyncSession,
    canonical_name: str,
    canonical_name_ar: str | None = None,
    cr_number: str | None = None,
    city: str | None = None,
    domain: str | None = None,
    phone: str | None = None,
    email: str | None = None,
    industry: str | None = None,
    country: str = "Saudi Arabia",
) -> str:
    """Create a global company and return the Global ID (G-C-XXXXXXXX)."""
    global_id = generate_global_id("C")
    slug = global_id.lower().replace("g-c-", "gc-")
    now = _now()

    await session.execute(
        text(
            "INSERT INTO md_global_companies "
            "(id, slug, canonical_name, canonical_name_ar, cr_number, city, domain, "
            "phone, email, industry, country, status, source_count, created_at, updated_at) "
            "VALUES (:id, :slug, :name, :name_ar, :cr, :city, :domain, "
            ":phone, :email, :industry, :country, 'active', 1, :now, :now)"
        ),
        {
            "id": global_id,
            "slug": slug,
            "name": canonical_name,
            "name_ar": canonical_name_ar,
            "cr": cr_number,
            "city": city,
            "domain": domain,
            "phone": phone,
            "email": email,
            "industry": industry,
            "country": country,
            "now": now,
        },
    )

    return global_id


async def create_global_person_from_muhide(
    session: AsyncSession,
    canonical_name: str,
    email: str | None = None,
    phone: str | None = None,
    company_global_id: str | None = None,
    job_title: str | None = None,
) -> str:
    """Create a global person and return the Global ID (G-P-XXXXXXXX)."""
    global_id = generate_global_id("P")
    slug = global_id.lower().replace("g-p-", "gp-")
    now = _now()

    await session.execute(
        text(
            "INSERT INTO md_global_people "
            "(id, slug, canonical_name, email, phone, company_global_id, job_title, "
            "status, source_count, created_at, updated_at) "
            "VALUES (:id, :slug, :name, :email, :phone, :company_id, :title, "
            "'active', 1, :now, :now)"
        ),
        {
            "id": global_id,
            "slug": slug,
            "name": canonical_name,
            "email": email,
            "phone": phone,
            "company_id": company_global_id,
            "title": job_title,
            "now": now,
        },
    )

    return global_id


# ── Legacy ID Mapping ───────────────────────────────────────────────────────


async def register_legacy_mapping(
    session: AsyncSession,
    legacy_id_type: str,
    legacy_id: str,
    global_entity_type: str,
    global_entity_id: str,
    confidence: float = 1.0,
) -> str | None:
    """Register a legacy→global ID mapping. Idempotent (ON CONFLICT DO NOTHING).

    Returns the mapping ID if created, None if already exists.
    """
    mapping_id = str(uuid.uuid4())
    now = _now()

    result = await session.execute(
        text(
            "INSERT INTO md_legacy_id_mappings "
            "(id, legacy_id_type, legacy_id, global_entity_type, global_entity_id, confidence, created_at) "
            "VALUES (:id, :type, :legacy_id, :entity_type, :entity_id, :confidence, :now) "
            "ON CONFLICT (legacy_id_type, legacy_id) DO NOTHING "
            "RETURNING id"
        ),
        {
            "id": mapping_id,
            "type": legacy_id_type,
            "legacy_id": legacy_id,
            "entity_type": global_entity_type,
            "entity_id": global_entity_id,
            "confidence": confidence,
            "now": now,
        },
    )

    row = result.mappings().first()
    return row["id"] if row else None


# ── Field Provenance ─────────────────────────────────────────────────────────


async def record_field_provenance(
    session: AsyncSession,
    global_entity_id: str,
    field_name: str,
    field_value: str,
    source_row_id: str,
    source_file_id: str,
    evidence_tier: str,
    signal_name: str,
    selection_reason: str = "ingested_from_source",
) -> str:
    """Record field provenance. Supersedes existing current value if higher authority."""
    from app.modules.entity_resolution.field_provenance import compute_authority_score

    now = _now()
    authority = compute_authority_score(signal_name)
    prov_id = str(uuid.uuid4())

    # Check existing current value
    existing = await session.execute(
        text(
            "SELECT id, authority_score FROM md_field_provenance "
            "WHERE global_entity_id = :entity_id AND field_name = :field_name AND is_current = true"
        ),
        {"entity_id": global_entity_id, "field_name": field_name},
    )
    existing_row = existing.mappings().first()

    if existing_row and existing_row["authority_score"] >= authority:
        # Record as historical only
        await session.execute(
            text(
                "INSERT INTO md_field_provenance "
                "(id, global_entity_id, field_name, field_value, source_row_id, source_file_id, "
                "observed_at, evidence_tier, authority_score, selection_reason, conflict_status, "
                "is_current, created_at) "
                "VALUES (:id, :entity_id, :field, :value, :src_row, :src_file, :now, "
                ":tier, :authority, :reason, 'superseded', false, :now)"
            ),
            {
                "id": prov_id, "entity_id": global_entity_id, "field": field_name,
                "value": field_value, "src_row": source_row_id, "src_file": source_file_id,
                "now": now, "tier": evidence_tier, "authority": authority, "reason": selection_reason,
            },
        )
        return prov_id

    # Supersede existing
    if existing_row:
        await session.execute(
            text(
                "UPDATE md_field_provenance SET is_current = false, superseded_at = :now "
                "WHERE global_entity_id = :entity_id AND field_name = :field_name AND is_current = true"
            ),
            {"entity_id": global_entity_id, "field_name": field_name, "now": now},
        )

    # Insert new current
    await session.execute(
        text(
            "INSERT INTO md_field_provenance "
            "(id, global_entity_id, field_name, field_value, source_row_id, source_file_id, "
            "observed_at, evidence_tier, authority_score, selection_reason, conflict_status, "
            "is_current, created_at) "
            "VALUES (:id, :entity_id, :field, :value, :src_row, :src_file, :now, "
            ":tier, :authority, :reason, 'none', true, :now)"
        ),
        {
            "id": prov_id, "entity_id": global_entity_id, "field": field_name,
            "value": field_value, "src_row": source_row_id, "src_file": source_file_id,
            "now": now, "tier": evidence_tier, "authority": authority, "reason": selection_reason,
        },
    )

    return prov_id


# ── MUHIDE Resolution Candidate Validation ──────────────────────────────────


async def load_resolution_candidates(
    csv_path: str,
) -> list[dict[str, Any]]:
    """Load MUHIDE_resolution_candidates.csv as validation fixture."""
    candidates = []
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            candidates.append(dict(row))
    return candidates


async def validate_candidates_vs_phase3(
    session: AsyncSession,
    candidates: list[dict[str, Any]],
) -> dict[str, Any]:
    """Compare MUHIDE analytical recommendations against Phase 3 decisions.

    Returns a discrepancy report.
    """
    report = {
        "total_candidates": len(candidates),
        "matches": 0,
        "review_required": 0,
        "separate": 0,
        "vetoed": 0,
        "discrepancies": [],
    }

    for cand in candidates:
        muhide_decision = cand.get("recommended_decision", "UNKNOWN")
        evidence_class = cand.get("evidence_class", "UNKNOWN")
        source_independence = cand.get("source_independence", "UNKNOWN")

        # Map MUHIDE decision to SalesOS equivalent
        if muhide_decision == "MATCH":
            report["matches"] += 1
        elif muhide_decision == "REVIEW_REQUIRED":
            report["review_required"] += 1
        elif muhide_decision == "SEPARATE":
            report["separate"] += 1
        elif muhide_decision == "VETOED":
            report["vetoed"] += 1

        # Check if Phase 3 would agree
        phase3_expected = _predict_phase3_decision(evidence_class, source_independence)
        if phase3_expected != muhide_decision:
            report["discrepancies"].append({
                "record_a": cand.get("record_a"),
                "record_b": cand.get("record_b"),
                "muhide_decision": muhide_decision,
                "phase3_expected": phase3_expected,
                "evidence_class": evidence_class,
                "source_independence": source_independence,
                "reason": _explain_discrepancy(muhide_decision, phase3_expected, evidence_class),
            })

    return report


def _predict_phase3_decision(evidence_class: str, source_independence: str) -> str:
    """Predict what Phase 3 would decide based on evidence class."""
    if evidence_class == "GOVERNMENT_ANCHOR_CONFLICT":
        return "VETOED"
    if evidence_class == "FUZZY":
        return "REVIEW_REQUIRED"  # Fuzzy-only never auto-merges
    if evidence_class in ("STRONG_DETERMINISTIC", "NORMALIZED_EXACT"):
        if source_independence == "INDEPENDENT":
            return "MATCH"  # Independent strong sources
        return "REVIEW_REQUIRED"  # Same source, not independent
    if evidence_class == "WEAK_DETERMINISTIC":
        return "REVIEW_REQUIRED"
    return "REVIEW_REQUIRED"


def _explain_discrepancy(muhide: str, phase3: str, evidence: str) -> str:
    """Explain why MUHIDE and Phase 3 decisions differ."""
    if evidence == "FUZZY" and muhide == "REVIEW_REQUIRED" and phase3 == "REVIEW_REQUIRED":
        return "Both agree: fuzzy-only → REVIEW_REQUIRED (never auto-merge)"
    if evidence == "FUZZY":
        return f"Phase 3: fuzzy-only → REVIEW_REQUIRED; MUHIDE: {muhide}"
    if muhide == "MATCH" and phase3 == "REVIEW_REQUIRED":
        return "Phase 3 requires independent sources; MUHIDE matched on weaker evidence"
    return f"MUHIDE: {muhide}, Phase 3 predicted: {phase3}, Evidence: {evidence}"


# ── Historical Review Cluster Preservation ───────────────────────────────────


async def preserve_review_clusters(
    session: AsyncSession,
    csv_path: str,
    tenant_id: str,
) -> int:
    """Preserve MUHIDE historical review clusters as audit information.

    Loads 04_Entity_Resolution_Review.csv and stores as source rows
    with entity_type='review_cluster' for historical traceability.
    """
    count = 0
    now = _now()

    try:
        with open(csv_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            batch = []

            for idx, row in enumerate(reader):
                batch.append({
                    "id": str(uuid.uuid4()),
                    "tenant_id": tenant_id,
                    "file_id": "",  # Will be set if file is registered
                    "source_id": "muhide_review_cluster",
                    "source_record_id": row.get("Old Master Account ID", f"CLUSTER-{idx}"),
                    "row_number": idx,
                    "payload": json.dumps(dict(row), ensure_ascii=False, default=str),
                    "entity_type": "review_cluster",
                    "now": now,
                })

                if len(batch) >= BATCH_SIZE:
                    await session.execute(
                        text(
                            "INSERT INTO md_source_rows "
                            "(id, tenant_id, source_file_id, source_id, source_record_id, "
                            "row_number, raw_payload, entity_type, resolution_status, created_at) "
                            "VALUES (:id, :tenant_id, :file_id, :source_id, :source_record_id, "
                            ":row_number, CAST(:payload AS JSONB), :entity_type, 'historical', :now) "
                            "ON CONFLICT (source_id, source_record_id) DO NOTHING"
                        ),
                        batch,
                    )
                    count += len(batch)
                    batch.clear()

            # Flush remaining
            if batch:
                await session.execute(
                    text(
                        "INSERT INTO md_source_rows "
                        "(id, tenant_id, source_file_id, source_id, source_record_id, "
                        "row_number, raw_payload, entity_type, resolution_status, created_at) "
                        "VALUES (:id, :tenant_id, :file_id, :source_id, :source_record_id, "
                        ":row_number, CAST(:payload AS JSONB), :entity_type, 'historical', :now) "
                        "ON CONFLICT (source_id, source_record_id) DO NOTHING"
                    ),
                    batch,
                )
                count += len(batch)

    except Exception as e:
        pass  # Non-fatal: historical preservation is best-effort

    return count
