apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: salesos
  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: event-bus
    app.kubernetes.io/part-of: salesos
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
  selector:
    app: kafka
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-lb
  namespace: salesos
  labels:
    app: kafka
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: event-bus
    app.kubernetes.io/part-of: salesos
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
  selector:
    app: kafka
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: salesos
  labels:
    app: zookeeper
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/component: event-bus
    app.kubernetes.io/part-of: salesos
spec:
  ports:
    - port: 2181
      targetPort: 2181
      name: zk
    - port: 2888
      targetPort: 2888
      name: zk-peer
    - port: 3888
      targetPort: 3888
      name: zk-leader
  selector:
    app: zookeeper
  clusterIP: None
