apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: salesos
  labels:
    app: neo4j
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: salesos
spec:
  ports:
    - port: 7474
      targetPort: 7474
      name: http
    - port: 7687
      targetPort: 7687
      name: bolt
  selector:
    app: neo4j
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-lb
  namespace: salesos
  labels:
    app: neo4j
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: salesos
spec:
  ports:
    - port: 7687
      targetPort: 7687
      name: bolt
  selector:
    app: neo4j
  type: ClusterIP
