#!/usr/bin/env python3
"""Generate PostgreSQL Row-Level Security (RLS) policies for tenant-scoped tables.

STORY-02-01 (Sprint 02, Phase 0): "RLS design, start" — this script targets a
10-table pilot set only. It does not enable RLS on the other ~62 tenant-scoped
tables and it is never invoked automatically (not from CI, not from Alembic,
not from application startup). The full 72-table rollout is Sprint 03's
STORY-02-01 ("RLS rollout, complete"), tracked separately in
docs/program/SPRINT_PLAN/Sprint-03.md.

Usage (local/docker):
  python scripts/generate_rls_policies.py                       # print SQL, default, side-effect free
  python scripts/generate_rls_policies.py --tables companies users
  python scripts/generate_rls_policies.py --apply --database-url postgresql+asyncpg://... \
      --yes-i-understand-this-affects-live-queries

Never runs automatically. Never targets production by itself — --apply
requires both an explicit --database-url and the long confirmation flag.

Why FORCE ROW LEVEL SECURITY, why current_setting(..., true), why USING +
WITH CHECK, why the ::text cast on both sides — see the docstring on
generate_policy_sql() below; read it before changing the template.
"""
from __future__ import annotations

import argparse
import sys

# ---------------------------------------------------------------------------
# Canonical implementation lives in app.alembic.lib.rls.
# Re-export everything so this module stays backward-compatible for
# development/CLI usage and existing ``from scripts.generate_rls_policies
# import ...`` statements outside of Alembic migrations.
# ---------------------------------------------------------------------------
from app.alembic.lib.rls import (  # noqa: F401
    ALL_TENANT_TABLES,
    CATEGORY_B1_JOIN_TABLES,
    CATEGORY_B2_JOIN_TABLES,
    CATEGORY_B3_JOIN_TABLES,
    CATEGORY_B4_JOIN_TABLES,
    CATEGORY_B5_JOIN_TABLES,
    CATEGORY_B6_JOIN_TABLES,
    CATEGORY_B7_JOIN_TABLES,
    DB05_DEFERRED_8_TENANT_TABLES,
    SESSION_VAR,
    generate_join_policy_sql,
    generate_policy_sql,
)


def generate_all_sql(tables: list[str] | None = None) -> str:
    tables = tables if tables is not None else ALL_TENANT_TABLES
    parts = [
        "-- Generated by scripts/generate_rls_policies.py",
        "-- STORY-02-01 (Sprint 02): pilot scope only, 10 tables. See module docstring.",
        "--",
        "-- WARNING: do not apply this to a database real application traffic",
        "-- depends on until the app's DB session layer sets `app.tenant_id`",
        "-- per request (Sprint 03, STORY-02-01 'RLS rollout, complete'). Until",
        "-- then, enabling this on a live-serving table makes every query",
        "-- against it return zero rows, for every tenant, silently.",
        "",
    ]
    for t in tables:
        parts.append(f"-- {t}")
        parts.append(generate_policy_sql(t))
    return "\n".join(parts)


async def _apply(database_url: str, tables: list[str]) -> None:
    from sqlalchemy import text
    from sqlalchemy.ext.asyncio import create_async_engine

    engine = create_async_engine(database_url)
    try:
        async with engine.begin() as conn:
            for t in tables:
                await conn.execute(text(generate_policy_sql(t)))
    finally:
        await engine.dispose()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--tables", nargs="*", default=None, help="Override the pilot table list (default: the 10-table Sprint 02 set).")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Execute the generated DDL against --database-url instead of printing it.",
    )
    parser.add_argument("--database-url", default=None, help="asyncpg-style SQLAlchemy URL. Required with --apply.")
    parser.add_argument(
        "--yes-i-understand-this-affects-live-queries",
        action="store_true",
        dest="confirmed",
        help="Required with --apply. See the WARNING in generate_all_sql().",
    )
    args = parser.parse_args(argv)

    tables = args.tables if args.tables is not None else ALL_TENANT_TABLES

    if args.apply:
        if not args.confirmed:
            print(
                "Refusing to --apply without --yes-i-understand-this-affects-live-queries.\n"
                "Enabling RLS on a table application traffic depends on, before the app sets\n"
                "`app.tenant_id` per request (Sprint 03 work), makes every query against that\n"
                "table return zero rows. This flag exists so that cannot happen by accident.",
                file=sys.stderr,
            )
            return 2
        if not args.database_url:
            print("Refusing to --apply without --database-url.", file=sys.stderr)
            return 2
        import asyncio

        asyncio.run(_apply(args.database_url, tables))
        print(f"Applied RLS policies to {len(tables)} table(s): {', '.join(tables)}")
        return 0

    print(generate_all_sql(tables))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
