apiVersion: v1
kind: Namespace
metadata:
  name: salesos
  labels:
    name: salesos
    environment: production
    managed-by: kustomize
    app.kubernetes.io/name: salesos
    app.kubernetes.io/part-of: salesos
