apiVersion: v1
kind: ResourceQuota
metadata:
  name: salesos-quota
  namespace: salesos
  labels:
    app.kubernetes.io/name: salesos-quota
    app.kubernetes.io/component: quota
    app.kubernetes.io/part-of: salesos
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "16Gi"
    limits.cpu: "16"
    limits.memory: "32Gi"
    persistentvolumeclaims: "10"
    pods: "30"
