"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { getOpportunityNBA, refreshOpportunityNBA, type OpportunityNBA } from "@/lib/api";
import { getTenantId } from "@/lib/hooks/useTenant";
import { ErrorState, LoadingState } from "../../_components/states";

function actionLabel(value: string): string {
  return value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function NbaDetails({ nba }: { nba: OpportunityNBA }) {
  return (
    <div className="space-y-4" data-testid="deal-nba-details">
      <div className="rounded-lg border border-[var(--border-default)] p-4">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <p className="text-xs font-medium uppercase tracking-wide text-[var(--text-muted)]">
              Recommended next action
            </p>
            <h2 className="mt-1 text-lg font-semibold text-[var(--text-primary)]">
              {actionLabel(nba.action)}
            </h2>
          </div>
          <span className="rounded-full border border-[var(--border-default)] px-2 py-1 text-xs text-[var(--text-secondary)]">
            {Math.round(nba.confidence * 100)}% · {actionLabel(nba.confidence_label)} confidence
          </span>
        </div>
        <p className="mt-3 text-sm text-[var(--text-secondary)]">{nba.reason}</p>
        <p className="mt-2 text-xs text-[var(--text-muted)]">
          Generated by the {actionLabel(nba.source)} decision path. Review the evidence before acting.
        </p>
      </div>

      {nba.evidence.length > 0 ? (
        <section aria-labelledby="deal-nba-evidence-title" className="space-y-2">
          <h3 id="deal-nba-evidence-title" className="text-sm font-medium text-[var(--text-primary)]">
            Evidence used
          </h3>
          <ul className="space-y-2">
            {nba.evidence.map((item, index) => (
              <li key={`${item.type}-${item.source}-${index}`} className="rounded-md bg-[var(--bg-secondary)] p-3">
                <p className="text-sm text-[var(--text-primary)]">{item.description}</p>
                <p className="mt-1 text-xs text-[var(--text-muted)]">
                  {actionLabel(item.type)} · {item.source} · {Math.round(item.confidence * 100)}% source confidence
                </p>
              </li>
            ))}
          </ul>
        </section>
      ) : (
        <p className="text-sm text-[var(--text-muted)]">This recommendation has no attached evidence items.</p>
      )}

      {nba.potential_risks.length > 0 ? (
        <section aria-labelledby="deal-nba-risks-title" className="space-y-2">
          <h3 id="deal-nba-risks-title" className="text-sm font-medium text-[var(--text-primary)]">
            Potential risks
          </h3>
          <ul className="list-disc space-y-1 pl-5 text-sm text-[var(--text-secondary)]">
            {nba.potential_risks.map((risk, index) => (
              <li key={`${risk.type}-${index}`}>
                <span className="font-medium">{actionLabel(risk.level)}:</span> {risk.description}
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      {nba.alternatives.length > 0 ? (
        <section aria-labelledby="deal-nba-alternatives-title" className="space-y-2">
          <h3 id="deal-nba-alternatives-title" className="text-sm font-medium text-[var(--text-primary)]">
            Other options
          </h3>
          <ul className="space-y-1 text-sm text-[var(--text-secondary)]">
            {nba.alternatives.map((alternative, index) => (
              <li key={`${alternative.action}-${index}`}>
                {actionLabel(alternative.action)} — {alternative.reason} ({Math.round(alternative.confidence * 100)}%)
              </li>
            ))}
          </ul>
        </section>
      ) : null}
    </div>
  );
}

export function DealNbaTab({ opportunityId }: { opportunityId: string }) {
  const tenantId = getTenantId();
  const queryClient = useQueryClient();
  const queryKey = ["opportunityNba", opportunityId];
  const query = useQuery({
    queryKey,
    queryFn: () => getOpportunityNBA(opportunityId, tenantId),
    enabled: Boolean(opportunityId && tenantId),
    staleTime: 30_000,
  });

  const refresh = useMutation({
    mutationFn: () => refreshOpportunityNBA(opportunityId, tenantId),
    onSuccess: (result) => queryClient.setQueryData(queryKey, result),
  });

  if (query.isLoading) return <LoadingState label="Loading next best action…" />;
  if (query.isError) {
    return (
      <ErrorState
        title="Could not load next best action"
        description={query.error instanceof Error ? query.error.message : "Request failed"}
        onRetry={() => void query.refetch()}
      />
    );
  }
  if (!query.data) return null;

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <p className="text-sm text-[var(--text-secondary)]">
          Recommendation for this opportunity. Refresh recomputes it from the current CRM record and recent activity.
        </p>
        <button
          type="button"
          onClick={() => refresh.mutate()}
          disabled={refresh.isPending}
          className="rounded-md border border-[var(--border-default)] px-3 py-2 text-sm text-[var(--text-primary)] hover:bg-[var(--bg-secondary)] disabled:opacity-50"
        >
          {refresh.isPending ? "Refreshing…" : "Refresh recommendation"}
        </button>
      </div>
      {refresh.isError ? (
        <p role="alert" className="text-sm text-[var(--status-danger,#dc2626)]">
          {refresh.error instanceof Error ? refresh.error.message : "Could not refresh recommendation"}
        </p>
      ) : null}
      <NbaDetails nba={query.data} />
      <p className="text-xs text-[var(--text-muted)]">
        A recommendation does not send a message or change the opportunity. Confirm the evidence and complete any action yourself.
      </p>
    </div>
  );
}
